### ISSUE TITLE
fbuffer.h:23: error 249: duplicate parameter name x

### ISSUE THREAD

**Issue by klata82** [samyk/opensesame#10]
You get an error at compilation time, because of a typo in **fbuffer.h**
The last function parameter should be renamed.

fbuffer.h:23: error 249: duplicate parameter name x for function fb_horizline

//! Draw a horizontal line.
void fb_horizline(**u16 x**, u16 y, **u16 x**);

**Comment by samyk** [comment]
Thanks! Wasn't erroring in sdcc 3.4.0, resolved now.
