### ISSUE TITLE
SDCC wont compile

### ISSUE THREAD

**Issue by GMDII** [samyk/opensesame#13]
Ok tried several ways to compile this file but this is a garbage it spits out. 

:~/IMME/opensesame$ sudo sdcc opensesame.c
In file included from opensesame.c:80:
display.h:69:1: warning: "NOP" redefined
In file included from /usr/local/bin/../share/sdcc/include/mcs51/cc1110.h:29,
                 from opensesame.c:76:
/usr/local/bin/../share/sdcc/include/mcs51/compiler.h:88:1: error: this is the location of the previous definition

?ASlink-Warning-Undefined Global '_port1_isr' referenced by module 'opensesame'

?ASlink-Warning-Undefined Global '_xtalClock' referenced by module 'opensesame'

?ASlink-Warning-Undefined Global '_fb_bitblt' referenced by module 'opensesame'

?ASlink-Warning-Undefined Global '_printrl_PARM_2' referenced by module 'opensesame'

?ASlink-Warning-Undefined Global '_keyscan' referenced by module 'opensesame'

?ASlink-Warning-Undefined Global '_printrlc' referenced by module 'opensesame'

?ASlink-Warning-Undefined Global '_configureSPI' referenced by module 'opensesame'

?ASlink-Warning-Undefined Global '_fb_blank' referenced by module 'opensesame'

?ASlink-Warning-Undefined Global '_LCDPowerSave' referenced by module 'opensesame'

?ASlink-Warning-Undefined Global '_nyan' referenced by module 'opensesame'

?ASlink-Warning-Undefined Global '_printl_PARM_2' referenced by module 'opensesame'

?ASlink-Warning-Undefined Global '_setIOPorts' referenced by module 'opensesame'

?ASlink-Warning-Undefined Global '_sleepMillis' referenced by module 'opensesame'

?ASlink-Warning-Undefined Global '_clear' referenced by module 'opensesame'

?ASlink-Warning-Undefined Global '_fb_bitblt_PARM_2' referenced by module 'opensesame'

?ASlink-Warning-Undefined Global '_fb_flush' referenced by module 'opensesame'

?ASlink-Warning-Undefined Global '_getkey' referenced by module 'opensesame'

?ASlink-Warning-Undefined Global '_fb_bitblt_PARM_3' referenced by module 'opensesame'

?ASlink-Warning-Undefined Global '_fb_bitblt_PARM_4' referenced by module 'opensesame'

?ASlink-Warning-Undefined Global '_printrl' referenced by module 'opensesame'

?ASlink-Warning-Undefined Global '_printrlc_PARM_2' referenced by module 'opensesame'

?ASlink-Warning-Undefined Global '_db_send' referenced by module 'opensesame'

?ASlink-Warning-Undefined Global '_printrlc_PARM_3' referenced by module 'opensesame'

?ASlink-Warning-Undefined Global '_LCDReset' referenced by module 'opensesame'

?ASlink-Warning-Undefined Global '_sleep' referenced by module 'opensesame'

?ASlink-Warning-Undefined Global '_printl' referenced by module 'opensesame'

**Comment by samyk** [comment]
Ah, we just emailed but didn't know the errors were straight sdcc. Did you try `make`?

**Comment by GMDII** [comment]
Yup ! `Make` worked

Thanks.
