### ISSUE TITLE
Hard Coded frequencies? 

### ISSUE THREAD

**Issue by GMDII** [samyk/opensesame#14]
two things going on. 

318 MHz is transmitting forever and never stops. 

I commented that Freq out of garages.h but that seems to not ignore 318Mhz. so are these frequencies hard coded in RF.c? 

I do have RFIM = RFIM_IM_DONE implemented so i hope that is not messing with an IRQ or something.

**Comment by GMDII** [comment]
Figured it out. Just changed:

From:  `for (key = 0; key < sizeof(garages); key++)`
To: `for (key = 0; key <= 2; key++)`

this prevents 318Mhz from executing. 
Still don't know why this frequency never ends though.

**Comment by Ivan275g4** [comment]
It takes a white for the 318 frequency to finish. Don't remember exactly but 18mins comes to mind,  You should be able to delete or comment it out of garages.h without problems Did you save garages.h before compiling?
