### ISSUE TITLE
Frequency offset for inaccurate IM-ME's

### ISSUE THREAD

**Issue by pickeditmate** [samyk/opensesame#16]
Hi Samy,

I have 3 IM-ME's one of which is perfectly on frequency when checking with Michael Ossmann's specan.hex but the other 2 are about 15-20MHz off. 

For reference:
The accurate one has a serial of 33870P (and has an FCCID printed on top) (So likely the newer of the three)
Meanwhile the 2 inaccurate ones have serial of 15680P and 21280P (and no FCCID written on either of them)

My question is, when using opensesame on those 2 inaccurate imme's will I need to adjust the TX frequency for a 433.92mhz garage/doorbell to be 417 ?

Thank you

**Comment by samyk** [comment]
No FCC ID? Sounds like knockoffs. You're saying RX is off but I don't know if that means TX will be off. I would suggest using the good one to RX while each bad one TX's to tune them.
