### ISSUE TITLE
Question then more on an issue

### ISSUE THREAD

**Issue by gh0stshell** [samyk/opensesame#2]
I am getting my IM-ME tomorrow. Do I need to use the 50$ GoodFET to program? Or can I use a USB to UART, Serial to pin out, or USB to FTDI that I already have?

**Comment by chrisjunlee** [comment]
You will need a JTAG programmer (GoodFET, Busblaster, or their $5 knockoffs).

Here's a cheap way using an Arduino: http://daveshacks.blogspot.com/2010/01/im-me-hacking.html

**Comment by gh0stshell** [comment]
Thanks!

**Comment by gh0stshell** [comment]
Will this work, I can order it now and get it tomorrow when my IM-ME arrives so I dont have to wait to program it.

**Comment by gh0stshell** [comment]
http://www.amazon.com/gp/product/B013E45XOQ?psc=1&redirect=true&ref_=ox_sc_act_title_1&smid=AMO06BSLP8P1W

**Comment by gh0stshell** [comment]
NVM, I bought the following just to be safe:

Seeedstudio Bus Blaster v4
Bus Pirate

Hoping one of the 2 works or both and then return the one not needed.

**Comment by chrisjunlee** [comment]
Also be sure to read up on Travis's post: http://travisgoodspeed.blogspot.com/2010/03/im-me-goodfet-wiring-tutorial.html

**Comment by gh0stshell** [comment]
how to flash using the the 2 flashers I bought? The article you posted only shows how to flash using GoodFET.....

**Comment by gh0stshell** [comment]
I bought a GoodFET and will be here tomorrow, one of the 2 devices did not have the pins as shown by the GoodFET, the other seems like it may work, I read the docs and it takes a .hex to flash the device from what I can tell. I did not see one in the repo. I work IT Security for an asset management company and this device will allow me to show them how old their security systems are and give proof moving forward to by better systems for our properties. I have already done a test using an SDR and a YARD Stick One, but the powers that be will think its amazing using this device.

**Comment by JL01152** [comment]
I've been reading over the code. Now I don't know much about coding but it seems like there's a lot missing from it. Not just "a little: bricked but a whole bunch missing. It looks too short. Please excuse me if I don't know what I'm talking about. I'm really new to coding and trying really hard to catch up to a somewhat acceptable level. I know I started very late. :/ All help "corrections" would be greatly appreciated.

**Comment by samyk** [comment]
I commend you for reading over unfamiliar code! However no, there is not a whole bunch missing. I hope you continue to pick it apart and figure out the bricked portion, and how it all works. Good luck!

**Comment by JL01152** [comment]
Well I've come a long way from when I decided to be interested in coding. Everything looked like gibberish to me. Now I actually spend long stretches delving deep into the code. Trying to make sense of it. I guess most of it is outside of my scope which is why I'm making effort in taking a heuristic approach to learning c and python. Most of which, I must say, came after following your hacks. Kind of embarrassing to admit my lack of coding comprehension really. Thanks for wishing me luck and for inadvertently giving me the motivation to undertake this seemingly impossible task. I hope it all starts clicking soon. lol

**Comment by samyk** [comment]
Nothing embarrassing at all, we all start learning from nil, and I think it's great that you're going over code that is slightly out of your current understanding -- it's one of the best ways to learn. Often lower level microcontroller code that is directly accessing registers can be pretty confusing if you're coming from even the same language but in higher level contexts like code running on top of an OS, but it isn't any more difficult, it's just different. A single register adjustment can kick off a number of different actions and be easy to miss -- I'd ensure you first understand how registers work and go from there.

**Comment by JL01152** [comment]
Duly noted. I'll keep you posted as if I make any progress. Thanks for the tips.

**Comment by TrendMend** [comment]
Hey any updates to this? I personally am not familiar with the language this is written in too well, but I am going to try to "unbrick" it, after porting it to another platform with a similar chipset...
