### ISSUE TITLE
Little Help

### ISSUE THREAD

**Issue by rogueops** [samyk/opensesame#4]
I know the the source is broken as a precaution. I am taking a C# class and would like to see if I can figure out what the issue is and just need a little help by pointing me to at least the file(s) to work on. I am not asking how to fix it, but a simple nudge in the direction of what I should start reviewing to use what I learned this semester.

**Comment by zjrubin** [comment]
I think that you need to implement a few functions declared in rf.c to get the code working, namely:
![image](https://user-images.githubusercontent.com/46578381/56855993-91a62c00-691f-11e9-9705-85015a86e640.png)

**Comment by gh0stshell** [comment]
Thanks so much! I will give it a whirl. Being a beginner with C this will
take a bit.

**Comment by TrendMend** [comment]
Hey any update to this? I am going to give it a shot as well, but I am brand new to C, so we will see how it goes...

**Comment by gh0stshell** [comment]
I have made progress, thought i bricked my HW, but its been so long since I have used it I forgot the what happens and the normal errors received when flashing, glad samy like me likes formatted code, i find it easy to follow, already learned 3 new things about C.

**Comment by Ivan275g4** [comment]
Anyone fixed the code? I'm having a very hard time getting this to do what it was intended to.

**Comment by JL01152** [comment]
I think it's missing the instructions that go in the braces of the fuctions mentioned by zrjubin. There is nothing there. So you basically have a car with no transmission.

**Comment by rogueops** [comment]
I agree after working on this off and on, if anyone knows any firmware for
this device that has any type of transmit function I may have an idea on
how to get it to work, just an idea that may work

**Comment by Ivan275g4** [comment]
@rogueops if you want to see a working transition, check out the "Garage" project, I believe that it's what this is based on. 
https://github.com/mossmann/im-me

**Comment by pickeditmate** [comment]
Running a diff with mossmans code may help you here. Have fun, I know I am!

**Comment by rogueops** [comment]
I got an idea and it was due to that, just have not had time to give
it a try, I will close this as its been open for a while and I have
good ideas to run with, thanks to all
