### ISSUE TITLE
Hardware and software setup

### ISSUE THREAD

**Issue by KonradLinkowski** [samyk/opensesame#8]
Hey @samyk , can you tell me what is the software and hardware setup that you are using in Veritasium video right here https://youtu.be/CNodxp9Jy4A?t=143? Couldn't find any info about that in your video.

**Comment by samyk** [comment]
Hardware: RTL-SDR/HackRF/USRP B210 (I forget which, all will work)
Spectrum analyzer: GQRX
IQ file inspection: Inspectrum
