### ISSUE TITLE
Dependencies and deployment tools

### ISSUE THREAD

**Issue by DanielSchetritt** [samyk/opensesame#9]
Hi there, thanks for sharing this repository! I think I may have figured out how to un-brick the code (unless I underestimated the complexity of the solution), but don't worry; I won't spoil it! 😄 

Apart from the IM-ME, a GoodFET/GreatFET, some wires to connect them, this repository, and the SDCC compiler; is there anything else I need to build and deploy this to actual hardware? I thought maybe that I need to get the C libraries for the TI CC1110, but I can't seem to find the `cc1110.h` library on the web.

Any help appreciated.

**Comment by samyk** [comment]
Thanks :) My cc1110.h was from my sdcc but I've just pushed it into the repo for you
https://github.com/samyk/opensesame/blob/master/cc1110.h
